import { Injectable } from "@angular/core";

@Injectable()
export class AppPermissions
{

  public readonly MASTER = 'MASTER';
  public readonly OFFICE_TIMELINE_VIEW = 'OFFICE_TIMELINE_VIEW';

  public readonly COCKPIT_TEAM_TASKS = 'COCKPIT_TEAM_TASKS';
  public readonly TEAM_CALENDAR = 'TEAM_CALENDAR';

  public readonly SPECIFICATION_MANUFACTURER_ANALYSIS = 'SPECIFICATION_MANUFACTURER_ANALYSIS';
  public readonly SPECIFICATION_MANUFACTURER_ANALYSIS_EXCEL = 'SPECIFICATION_MANUFACTURER_ANALYSIS_EXCEL';

  public readonly TASK_ANALYSIS_EXCEL = 'TASK_ANALYSIS_EXCEL';
  public readonly TASK_ANALYSIS_SHOW_ALL = 'TASK_ANALYSIS_SHOW_ALL';

  public readonly PROJECT_ANALYSIS = 'PROJECT_ANALYSIS';
  public readonly PROJECT_ANALYSIS_EXCEL = 'PROJECT_ANALYSIS_EXCEL';
  public readonly PROJECT_ANALYSIS_SHOW_ALL = 'PROJECT_ANALYSIS_SHOW_ALL';

  public readonly PROJECT_PROGRESS = 'PROJECT_PROGRESS';
  public readonly TEAM_PROGRESS = 'TEAM_PROGRESS';

  public readonly CONTACT_LIST = 'CONTACT_LIST';
  public readonly CONTACT_EDIT = 'CONTACT_EDIT';
  public readonly CONTACT_DELETE = 'CONTACT_DELETE';
  public readonly CONTACT_LEVEL_2 = 'CONTACT_LEVEL_2';
  public readonly CONTACT_LEVEL_3 = 'CONTACT_LEVEL_3';
  public readonly CONTACT_LEVEL_4 = 'CONTACT_LEVEL_4';
  public readonly CONTACT_CATEGORY_MASTER = 'CONTACT_CATEGORY_MASTER';
  public readonly CONTACT_PROJECT_VIEW = 'CONTACT_PROJECT_VIEW';
  public readonly CONTACT_WORKORDER_VIEW = 'CONTACT_WORKORDER_VIEW';
  public readonly CONTACT_WORKORDER_EDIT = 'CONTACT_WORKORDER_EDIT';
  public readonly CONTACT_WORKORDER_DELETE = 'CONTACT_WORKORDER_DELETE';

  public readonly CONTACT_PERSONAL_ACCOUNTS_VIEW = 'CONTACT_PERSONAL_ACCOUNTS_VIEW';
  public readonly CONTACT_PERSONAL_ACCOUNTS_EDIT = 'CONTACT_PERSONAL_ACCOUNTS_EDIT';
  public readonly CONTACT_ASSOCIATIONS_VIEW = 'CONTACT_ASSOCIATIONS_VIEW';
  public readonly CONTACT_ASSOCIATIONS_EDIT = 'CONTACT_ASSOCIATIONS_EDIT';
  public readonly CONTACT_ASSOCIATIONS_DELETE = 'CONTACT_ASSOCIATIONS_DELETE';
  public readonly CONTACT_NOTES_VIEW = 'CONTACT_NOTES_VIEW';
  public readonly CONTACT_NOTES_EDIT = 'CONTACT_NOTES_EDIT';
  public readonly CONTACT_ANALYSIS = 'CONTACT_ANALYSIS';
  public readonly CONTACT_ANALYSIS_EXCEL = 'CONTACT_ANALYSIS_EXCEL';
  public readonly CONTACT_ANALYSIS_SHOW_ALL = 'CONTACT_ANALYSIS_SHOW_ALL';

  public readonly PROJECT_LIST = 'PROJECT_LIST';
  public readonly PROJECT_EDIT = 'PROJECT_EDIT';
  public readonly PROJECT_DELETE = 'PROJECT_DELETE';
  public readonly PROJECT_ASSOCIATIONS_VIEW = 'PROJECT_ASSOCIATIONS_VIEW';
  public readonly PROJECT_ASSOCIATIONS_EDIT = 'PROJECT_ASSOCIATIONS_EDIT';
  public readonly PROJECT_ASSOCIATIONS_DELETE = 'PROJECT_ASSOCIATIONS_DELETE';
  public readonly PROJECT_NOTES_VIEW = 'PROJECT_NOTES_VIEW';
  public readonly PROJECT_NOTES_EDIT = 'PROJECT_NOTES_EDIT';
  public readonly PROJECT_INWARDS_VIEW = 'PROJECT_INWARDS_VIEW';
  public readonly PROJECT_INWARDS_EDIT = 'PROJECT_INWARDS_EDIT';
  public readonly PROJECT_PHOTOS_VIEW = 'PROJECT_PHOTOS_VIEW';
  public readonly PROJECT_PHOTOS_EDIT = 'PROJECT_PHOTOS_EDIT';
  public readonly PROJECT_STAGES_VIEW = 'PROJECT_STAGES_VIEW';
  public readonly PROJECT_STAGES_EDIT = 'PROJECT_STAGES_EDIT';
  public readonly PROJECT_STAGES_STATUS_EDIT = 'PROJECT_STAGES_STATUS_EDIT';
  public readonly PROJECT_STAGES_SPECIAL_EDIT = 'PROJECT_STAGES_SPECIAL_EDIT';
  public readonly PROJECT_STAGES_DELETE = 'PROJECT_STAGES_DELETE';
  public readonly PROJECT_STAGES_TARGET_DATE = 'PROJECT_STAGES_TARGET_DATE';
  public readonly PROJECT_TEAM_VIEW = 'PROJECT_TEAM_VIEW';
  public readonly PROJECT_TEAM_EDIT = 'PROJECT_TEAM_EDIT';
  public readonly PROJECT_TEAM_DELETE = 'PROJECT_TEAM_DELETE';
  public readonly PROJECT_STAGES_MASTER = 'PROJECT_STAGES_MASTER';
  public readonly PROJECT_MEETINGS_VIEW = 'PROJECT_MEETINGS_VIEW';
  public readonly PROJECT_SITE_VISITS_VIEW = 'PROJECT_SITE_VISITS_VIEW';
  public readonly PROJECT_EMAIL_VIEW = 'PROJECT_EMAIL_VIEW';
  public readonly PROJECT_DOCUMENTS_VIEW = 'PROJECT_DOCUMENTS_VIEW';
  public readonly PROJECT_DOCUMENTS_EDIT = 'PROJECT_DOCUMENTS_EDIT';
  public readonly PROJECT_DOCUMENTS_DELETE = 'PROJECT_DOCUMENTS_DELETE';
  public readonly PROJECT_DOCUMENTS_SETTINGS = 'PROJECT_DOCUMENTS_SETTINGS';
  public readonly PROJECT_BILLING_VIEW = 'PROJECT_BILLING_VIEW';
  public readonly PROJECT_BILLING_EDIT = 'PROJECT_BILLING_EDIT';
  public readonly PROJECT_BILL_FOLLOW_UP_VIEW = 'PROJECT_BILL_FOLLOW_UP_VIEW';
  public readonly PROJECT_BILL_FOLLOW_UP_EDIT = 'PROJECT_BILL_FOLLOW_UP_EDIT';
  public readonly PROJECT_SPECIAL_SHOW_ALL = 'PROJECT_SPECIAL_SHOW_ALL';
  public readonly PROJECT_TODO_VIEW = 'PROJECT_TODO_VIEW';
  public readonly PROJECT_BILLING_ANALYSIS_VIEW= 'PROJECT_BILLING_ANALYSIS_VIEW';
  public readonly PROJECT_BILLING_ANALYSIS_EXCEL_DOWNLOAD= 'PROJECT_BILLING_ANALYSIS_EXCEL_DOWNLOAD';
  public readonly PROJECT_WORKORDER_VIEW = 'PROJECT_WORKORDER_VIEW';
  public readonly PROJECT_WORKORDER_EDIT = 'PROJECT_WORKORDER_EDIT';
  public readonly PROJECT_WORKORDER_DELETE = 'PROJECT_WORKORDER_DELETE';
  public readonly PROJECT_WORKORDER_SERVICE_MASTER = 'PROJECT_WORKORDER_SERVICE_MASTER';
  public readonly PROJECT_OFFER_VIEW = 'PROJECT_OFFER_VIEW';
  public readonly PROJECT_OFFER_EDIT = 'PROJECT_OFFER_EDIT';
  public readonly PROJECT_OFFER_DELETE = 'PROJECT_OFFER_DELETE';
  public readonly PROJECT_STAGES_ANALYSIS = 'PROJECT_STAGES_ANALYSIS';

  public readonly SPECIFICATION_LIBRARY_LIST = 'SPECIFICATION_LIBRARY_LIST';
  public readonly SPECIFICATION_LIBRARY_EDIT = 'SPECIFICATION_LIBRARY_EDIT';
  public readonly SPECIFICATION_LIBRARY_DELETE = 'SPECIFICATION_LIBRARY_DELETE';
  public readonly SPECIFICATION_LIBRARY_AUDIT = 'SPECIFICATION_LIBRARY_AUDIT';
  public readonly SPECIFICATION_LIBRARY_VENDOR_EDIT = 'SPECIFICATION_LIBRARY_VENDOR_EDIT';
  public readonly SPECIFICATION_LIBRARY_VENDOR_DELETE = 'SPECIFICATION_LIBRARY_VENDOR_DELETE';
  public readonly SPECIFICATION_LIBRARY_VENDOR_LIST = 'SPECIFICATION_LIBRARY_VENDOR_LIST';

  public readonly SPECIFICATION_LIST = 'SPECIFICATION_LIST';
  public readonly SPECIFICATION_EDIT = 'SPECIFICATION_EDIT';
  public readonly SPECIFICATION_DELETE = 'SPECIFICATION_DELETE';
  public readonly SPECIFICATION_AREA_EDIT = 'SPECIFICATION_AREA_EDIT';
  public readonly SPECIFICATION_AREA_DELETE = 'SPECIFICATION_AREA_DELETE';

  public readonly TEAM_LIST = 'TEAM_LIST';
  public readonly TEAM_CONTACT_VIEW = 'TEAM_CONTACT_VIEW';
  public readonly TEAM_CONTACT_EDIT = 'TEAM_CONTACT_EDIT';
  public readonly TEAM_CONTACT_DELETE = 'TEAM_CONTACT_DELETE';
  public readonly TEAM_APPOINTMENTS_VIEW = 'TEAM_APPOINTMENTS_VIEW';
  public readonly TEAM_APPOINTMENTS_EDIT = 'TEAM_APPOINTMENTS_EDIT';
  public readonly TEAM_APPOINTMENTS_DELETE = 'TEAM_APPOINTMENTS_DELETE';
  public readonly TEAM_DOCUMENTS_VIEW = 'TEAM_DOCUMENTS_VIEW';
  public readonly TEAM_DOCUMENTS_EDIT = 'TEAM_DOCUMENTS_EDIT';
  public readonly TEAM_DOCUMENTS_DELETE = 'TEAM_DOCUMENTS_DELETE';
  public readonly TEAM_USER_MGMT = 'TEAM_USER_MGMT';
  public readonly TEAM_DOCUMENTS_SETTINGS = 'TEAM_DOCUMENTS_SETTINGS';
  public readonly TEAM_MANAGEMENT = 'TEAM_MANAGEMENT';
  public readonly TEAM_SPECIAL_SHOW_ALL = 'TEAM_SPECIAL_SHOW_ALL';

  public readonly WFTASK_SPECIAL_SHOW_ALL = 'WFTASK_SPECIAL_SHOW_ALL';
  public readonly WFTASK_LIST = 'WFTASK_LIST';

  public readonly TODO_LIST = 'TODO_LIST';
  public readonly TODO_EDIT = 'TODO_EDIT';
  public readonly TODO_DELETE = 'TODO_DELETE';
  public readonly TODO_SPECIAL_SHOW_ALL = 'TODO_SPECIAL_SHOW_ALL';
  public readonly TODO_SPECIAL_EDIT = 'TODO_SPECIAL_EDIT';
  public readonly TODO_SPECIAL_DELETE = 'TODO_SPECIAL_DELETE';
  public readonly TODO_MEDIA_UPLOAD = 'TODO_MEDIA_UPLOAD';
  public readonly TODO_ANALYSIS = 'TODO_ANALYSIS';

  public readonly IMAGE_LIBRARY_LIST = 'IMAGE_LIBRARY_LIST';
  public readonly IMAGE_LIBRARY_EDIT = 'IMAGE_LIBRARY_EDIT';
  public readonly IMAGE_LIBRARY_DELETE = 'IMAGE_LIBRARY_DELETE';
  public readonly IMAGE_LIBRARY_AUDIT = 'IMAGE_LIBRARY_AUDIT';

  public readonly MEETING_LIST = 'MEETING_LIST';
  public readonly MEETING_EDIT = 'MEETING_EDIT';
  public readonly MEETING_DELETE = 'MEETING_DELETE';
  public readonly MEETING_INSPECTION_EDIT = 'MEETING_INSPECTION_EDIT';
  public readonly MEETING_CNOTE_EDIT = 'MEETING_CNOTE_EDIT';
  public readonly MEETING_SPECIAL_SHOW_ALL = 'MEETING_SPECIAL_SHOW_ALL';
  public readonly MEETING_SPECIAL_EDIT = 'MEETING_SPECIAL_EDIT';
  public readonly MEETING_CREATE_EVENT = 'MEETING_CREATE_EVENT';
  public readonly MEETING_SPECIAL_DELETE = 'MEETING_SPECIAL_DELETE';
  public readonly MEETING_REVIVE = 'MEETING_REVIVE';
  public readonly MEETING_AGENDA_LIST = 'MEETING_AGENDA_LIST';

  //Sitevisit
  public readonly SITE_VISIT_LIST = 'SITE_VISIT_LIST';
  public readonly SITE_VISIT_EDIT = 'SITE_VISIT_EDIT';
  public readonly SITE_VISIT_DELETE = 'SITE_VISIT_DELETE';
  public readonly SITE_VISIT_INSPECTION_EDIT = 'SITE_VISIT_INSPECTION_EDIT';
  public readonly SITE_VISIT_CNOTE_EDIT = 'SITE_VISIT_CNOTE_EDIT';
  public readonly SITE_VISIT_SPECIAL_SHOW_ALL = 'SITE_VISIT_SPECIAL_SHOW_ALL';
  public readonly SITE_VISIT_SPECIAL_EDIT = 'SITE_VISIT_SPECIAL_EDIT';
  public readonly SITE_VISIT_CREATE_EVENT = 'SITE_VISIT_CREATE_EVENT';
  public readonly SITE_VISIT_SPECIAL_DELETE = 'SITE_VISIT_SPECIAL_DELETE';
  public readonly SITE_VISIT_REVIVE = 'SITE_VISIT_REVIVE';
  public readonly SITE_VISIT_AGENDA_LIST = 'SITE_VISIT_AGENDA_LIST';

  public readonly REQUEST_TICKET_LIST = 'REQUEST_TICKET_LIST';
  public readonly REQUEST_TICKET_EDIT = 'REQUEST_TICKET_EDIT';
  public readonly REQUEST_TICKET_DELETE = 'REQUEST_TICKET_DELETE';
  public readonly REQUEST_TICKET_SPECIAL_SHOW_ALL = 'REQUEST_TICKET_SPECIAL_SHOW_ALL';
  public readonly REQUEST_TICKET_SPECIAL_EDIT = 'REQUEST_TICKET_SPECIAL_EDIT';
  public readonly REQUEST_TICKET_SPECIAL_DELETE = 'REQUEST_TICKET_SPECIAL_DELETE';

  public readonly LEAVE_LIST = 'LEAVE_LIST';
  public readonly LEAVE_EDIT = 'LEAVE_EDIT';
  public readonly LEAVE_DELETE = 'LEAVE_DELETE';
  public readonly LEAVE_SPECIAL_EDIT = 'LEAVE_SPECIAL_EDIT';
  public readonly LEAVE_MASTER = 'LEAVE_MASTER';
  public readonly LEAVE_HOLIDAY_MASTER = 'LEAVE_HOLIDAY_MASTER';

  public readonly ASSET_VIEW = "ASSET_VIEW";
  public readonly ASSET_CREATE = "ASSET_CREATE";
  public readonly ASSET_EDIT = "ASSET_EDIT";
  public readonly ASSET_DELETE = "ASSET_DELETE";
  public readonly ASSET_ATTRIBUTE_MASTER = "ASSET_ATTRIBUTE_MASTER";
  public readonly ASSET_MAINTENANCE_EDIT = "ASSET_MAINTENANCE_EDIT";
  public readonly ASSET_MAINTENANCE_VIEW = "ASSET_MAINTENANCE_VIEW";
  public readonly PROJECT_GMAIL_VIEW = 'PROJECT_GMAIL_VIEW';
  public readonly PROJECT_ALLOWED_IP_BYPASS_VIEW = 'PROJECT_ALLOWED_IP_BYPASS_VIEW';
  public readonly ANALYSIS_LIST_VIEW = 'ANALYSIS_LIST_VIEW';
  public readonly TASK_VIEW = 'TASK_VIEW';

  public readonly PROJECT_FILE_DMS = 'PROJECT_FILE_DMS';
  public readonly FILE_DMS_DELETE = 'FILE_DMS_DELETE';
  public readonly FILE_DMS_FOLDER_EDIT = 'FILE_DMS_FOLDER_EDIT';
  public readonly FILE_DMS_FOLDER_ADD = 'FILE_DMS_FOLDER_ADD';
  public readonly FILE_DMS_SUB_FOLDER_ADD = 'FILE_DMS_SUB_FOLDER_ADD';

  public readonly CHECKLIST_VIEW = 'CHECKLIST_VIEW';
  public readonly CHECKLIST_EDIT = 'CHECKLIST_EDIT';
  public readonly GMAIL_DASHBOARD_VIEW = 'GMAIL_DASHBOARD_VIEW';
  public readonly FILE_DASHBOARD_VIEW = 'FILE_DASHBOARD_VIEW';
}
